export const pageUrls = {
  HOME: "/",
  AUTH: {
    SIGN_IN: "/auth/sign-in",
    SIGN_UP: "/auth/sign-up",
    FORGOT: "/auth/forgot",
    VERIFY: "/auth/verify",
    RESET_PASSWORD: "/auth/reset-password",
  },
  FEED: "/feed",
  POSTS: {
    CREATE: "/posts/create",
  },
  NOTIFICATIONS: "/notifications",
  MESSAGES: "/messages",
  STREAMS: "/streams",
  BOOKMARKS: "/bookmarks",
  SEARCH: "/search",
  LISTS: "/lists",
  SUBSCRIPTIONS: "/settings/subscriptions",
  PROFILE: "/testuser",
  MORE: "/more",
  BILLING: "/billing",
  SETTINGS: {
    ROOT: "/settings",
    PROFILE: "/settings/profile",
    ACCOUNT: "/settings/account",
    WALLET: "/settings/wallet",
    PAYMENTS: "/settings/payments",
    RATES: "/settings/rates",
    SUBSCRIPTIONS: "/settings/subscriptions",
    REFERRALS: "/settings/referrals",
    NOTIFICATIONS: "/settings/notifications",
    PRIVACY: "/settings/privacy",
    VERIFY: "/settings/verify",
  },
};
